### ISSUE TITLE
#1 Review - Botones en header no redireccionan

### ISSUE THREAD

**Issue by Marcosreuquen** [WASD6570/apx-m7#1]
Buenas, @WASD6570.

Estaba probando la web pero no me deja iniciar sesión. 
O sea, de los botones y opciones de la home, sólo me dejó ver mascotas cerca mío por mi ubicación (que no había ninguna jaja). Pero de las opciones del header no me redirige. 

Saludos.

**Comment by WASD6570** [comment]
Hola @Marcosreuquen 
Quedaron los botones del template del header (onda me colgue con sacarlos) esta disponible en este desafio solo la version mobile, es decir deje el menu de hamburguesa para todas las resoluciones, ya que en el modulo que viene hacemos este front con React.
Tambien agregué que cuando des la ubicacion se active la modalcard del login, decime si ahora te funciona porfa. Gracias!
