### ISSUE TITLE
#2 Review

### ISSUE THREAD

**Issue by Marcosreuquen** [WASD6570/apx-m7#2]
Buenas @WASD6570 

Excelente, la interfaz te quedó genial!

Te dejo algunos comentarios del código:

- Fijate que podrías migrar la lógica que pertenece a las librerías (algolia/sendgrid/cloudinary) a los controllers para sacar un poco de lógica de los endpoints. Lo ideal sería que el endpoint reciba lo que procesan los middlewares, llame a una función y devuelva el resultado nada más.
 Te quitarías porciones grandes de código como la siguiente del endpoint y quedaría más prolijo:
 https://github.com/WASD6570/apx-m7/blob/984efdc5a0f1a725af12d8623b6d3b13ec7ad13e/server/view/index.ts#L99-L118
 https://github.com/WASD6570/apx-m7/blob/984efdc5a0f1a725af12d8623b6d3b13ec7ad13e/server/view/index.ts#L205-L213

- Lo mismo podrías hacer con los middlewares. Tener un módulo aparte para declarar middlewares, importarlos en el index y que sólo tengas que llamarlo en los endpoints:
 https://github.com/WASD6570/apx-m7/blob/984efdc5a0f1a725af12d8623b6d3b13ec7ad13e/server/view/index.ts#L34-L68

- Sobre el front, está excelente, nada que decir solo que los modals y esto es genial: 
https://github.com/WASD6570/apx-m7/blob/984efdc5a0f1a725af12d8623b6d3b13ec7ad13e/public/state.ts#L174

**Felicitaciones!!!** :partying_face:

**Comment by WASD6570** [comment]
Buenisimo Marcos, ahora hago esos ajustes asi queda mejor :D
